### ISSUE TITLE
Server crash - ava.lang.ClassCastException: de.ellpeck.actuallyadditions.mod.tile.TileEntityGiantChest cannot be cast to gcewing.architecture.ShapeTE

### ISSUE THREAD

**Issue by ProsperCraft** [gcewing/ArchitectureCraft#6]
http://pastebin.com/Y3VaXy45

Modpack - Allthemods 1.35

ava.lang.ClassCastException: de.ellpeck.actuallyadditions.mod.tile.TileEntityGiantChest cannot be cast to gcewing.architecture.ShapeTE
    at gcewing.architecture.ShapeBlock.getLocalBounds(ShapeBlock.java:139)
    at gcewing.architecture.ShapeBlock.func_185496_a(ShapeBlock.java:96)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:443)
    at net.minecraft.block.Block.func_180646_a(Block.java:375)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:433)
    at net.minecraft.pathfinding.PathWorldListener.func_184378_a(SourceFile:59)
    at net.minecraft.pathfinding.PathWorldListener.func_184376_a(SourceFile:25)
    at net.minecraft.world.World.func_184138_a(World.java:415)
    at net.minecraft.world.World.func_72939_s(World.java:1873)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

**Comment by gcewing** [comment]
Addressed in 1.7.3.
